### ISSUE TITLE
Params

### ISSUE THREAD

**Issue by reagiova** [akanazawa/MRF#2]
If I want to test the code on my image, what are the parameters (uParams.mu_b, uParams.mu_f1, uParams.mu_f2)  that I use?

**Comment by akanazawa** [comment]
Ugh I don't recall cause I wrote this a loong time ago :p but judging from what's in [do_all.m](https://github.com/akanazawa/MRF/blob/master/do_all.m) I think I just eye-balled it and tried values until it looked reasonable. I suggest you try start with those values in do_all.m
